export default {
  '--Not Set--': '--не встановлено--',
  'About Jodit': 'Про Jodit',
  Advansed: 'Розширені',
  Align: 'Вирівнювання',
  'Align Center': 'По центру',
  'Align Justify': 'По ширині',
  'Align Left': 'По лівому краю',
  'Align Right': 'По правому краю',
  Alternative: 'Альтернативний текст (alt)',
  'Alternative text': 'Альтернативний текст',
  Anchor: 'Якір',
  'Are you shure?': 'Впевнений?',
  Background: 'Тло',
  Bold: 'Жирний-жирний-жирний, як поїзд пасажирний',
  Bottom: 'Донизу',
  Browse: 'Сервер',
  'Buy full version': 'Купити повну версію',
  Cancel: 'Скасувати',
  Center: 'По центру',
  'Change mode': 'Джерело',
  Classes: 'Класи',
  'Clear Formatting': 'Очистити форматування',
  Code: 'Код',
  'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': 'Авторські права © XDSoft.net - Чупурнов Валерій. Всі права захищено.',
  'Create directory': 'Створити теку',
  'Delete column': 'Видалити стовпчик',
  'Delete row': 'Видалити рядок',
  'Delete table': 'Видалити таблицю',
  'Drop image': 'Перетягни сюди зображення',
  'Empty cell': 'Очистити клітинку',
  'Enter Directory name': 'Введи назву теки',
  'Error on load folders': 'Не вдалось завантажити список тек',
  'Error on load list': 'Не вдалось завантажити список зображень',
  'File Browser': 'Браузер файлів',
  'Fill color or set the text color': 'Колір тла або тексту',
  'Font family': 'Шрифт',
  'Font size': 'Розмір шрифту',
  'For information about the license, please go to our website:': 'Щоб отримати інформацію про ліцензію, перейди на сайт:',
  'Free Non-commercial Version': 'Версія для некомерційного користування',
  'Heading 1': 'Заголовок 1',
  'Heading 2': 'Заголовок 2',
  'Heading 3': 'Заголовок 3',
  'Heading 4': 'Заголовок 4',
  Image: 'Зображення',
  'Image properties': 'Властивості зображення',
  Insert: 'Вставити',
  'Insert Horizontal Line': 'Горизонтальна лінія',
  'Insert Image': 'Зображення',
  'Insert Ordered List': 'Нумерований список',
  'Insert Unordered List': 'Ненумерований список',
  'Insert column after': 'Вставити стовпчик після',
  'Insert column before': 'Вставити стовпчик до',
  'Insert format block': 'Форматування',
  'Insert link': 'Посилання',
  'Insert row above': 'Вставити рядок вище',
  'Insert row below': 'Вставити рядок нижче',
  'Insert table': 'Таблиця',
  'Insert youtube/vimeo video': 'Відео',
  Italic: 'Похилий',
  'Jodit Editor': 'Редактор Jodit',
  'Jodit User\'s Guide': 'Jodit інструкція',
  Left: 'Зліва',
  Link: 'Посилання',
  Margins: 'Відступи',
  Middle: 'Посередині',
  Normal: 'Звичайний текст',
  Ok: 'Вйо',
  'Open editor in fullsize': 'Відкрити в повному розмірі',
  'Open in new tab': 'Відкрити у новій вкладці',
  'Open link in new tab': 'Відкрити у новому вікні',
  'Paint format': 'Формат фарби',
  'Paste as HTML': 'Вставити як HTML?',
  Quote: 'Цитата',
  Redo: 'Вперед',
  Right: 'Справа',
  Src: 'src',
  Styles: 'Стилі',
  Text: 'Текст',
  Title: 'Заголовок',
  Top: 'Вгорі',
  'Type something': 'Напиши шось',
  Undo: 'Назад',
  Upload: 'Завантажити',
  'Your code is similar to HTML. Paste as HTML?': 'Цей текст схожий на HTML. Вставити його як HTML?',
  bottom: 'внизу',
  'contains detailed help for using': 'містить детальну інформацію щодо користування',
  left: 'зліва',
  'or click': 'або натисни',
  right: 'справа',
  top: 'вгорі',
  'type name': 'введи назву',
};
